[package]
name = "frolic-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
eyre = "0.6.12"
frolic-ast.workspace = true
frolic-ir.workspace = true
frolic-parser = { version = "0.0.1", path = "../parser" }
frolic-utils.workspace = true
miette = { workspace = true, features = ["fancy"] }

[features]
default = ["rayon"]

rayon = ["frolic-parser/rayon", "frolic-ir/rayon"]
