[package]
name = "frolic-ir"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
arc-swap = { version = "1.7.1", features = ["weak"] }
frolic-utils = { version = "0.1.0", path = "../utils" }
generational-arena = "0.2.9"
intrusive-collections = { version = "0.9.6", features = ["nightly"] }
ouroboros = "0.18.3"
parking_lot = { version = "0.12.1", features = ["nightly"] }
portable-atomic = { version = "1.6.0", features = ["std"] }
