[package]
name = "frolic-ir"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
arc-swap = "1.7.1"
frolic-ast.workspace = true
frolic-utils.workspace = true
miette.workspace = true
rayon = { version = "1.10.0", optional = true }
parking_lot = { version = "0.12.1", features = ["nightly"] }
portable-atomic = { version = "1.6.0", features = ["std"] }
thiserror.workspace = true
thread_local = { version = "1.1.8", optional = true }

[features]
rayon = ["dep:rayon", "thread_local"]
