[package]
name = "frolic-parser"
version.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frolic-utils = { version = "0.1.0", path = "../utils" }
rayon = { version = "1.10.0", optional = true }
strum = { version = "0.26.2", features = ["derive", "phf"] }
thiserror.workspace = true
miette.workspace = true
unicode-ident = "1.0.12"
bstr = { version = "1.9.1", default-features = false }

[features]
rayon = ["dep:rayon"]
