[package]
name = "frolic-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxcar = "0.2.4"
miette.workspace = true
smallvec.workspace = true
